env: environments.defend.ZoneDefense
number_agents: 2
simultaneous_enemies: 6
enemy_creation_interval: 0
agent_speed: 1.0
enemy_speed: 1.0
grid_size: 30
base_radius: 1
agent_radius: 0.5
enemy_radius: 0.5
sim_step_size: 0.1
total_episode_time: 120
dones:
  - name: environments.conditions.MaxTimeExceededCondition
    kwargs:
      max_time: 120
  - name: environments.conditions.EnemyEnteredBaseCondition

rewards:
  - name: environments.reward.AgentInterceptionReward
    kwargs:
      weight: 1
  - name: environments.reward.EnemyEnteredBaseReward
    kwargs:
      weight: 1

conditions:
  - name: environments.conditions.AgentTaskCompleteCondition
  - name: environments.conditions.AgentInterception