env: environments.defend.ZoneDefense
number_agents: 2
simultaneous_enemies: 6
enemy_creation_interval: 2
agent_speed: 1.5
enemy_speed: 1
grid_size: 30
base_radius: 1
agent_radius: 0.5
enemy_radius: 0.5
sim_step_size: 0.1
total_episode_time: 120
reward_weights:
  AgentInterceptionReward: 1
  EnemyEnteredBaseReward: -1